# PostgreSQL Configuration
#
# Install the PostgreSQL driver
#   gem install pg
#
# Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] || "Aa123456&" %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: ruby_quickpay_development

test:
  <<: *default
  database: ruby_quickpay_test

production:
  primary: &primary_production
    <<: *default
    database: ruby_quickpay_production
    username: ruby_quickpay
    password: <%= ENV["RUBY_QUICKPAY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ruby_quickpay_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ruby_quickpay_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ruby_quickpay_production_cable
    migrations_paths: db/cable_migrate
